# Generated by Django 5.0.4 on 2024-04-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_no', models.CharField(max_length=255)),
                ('location_id', models.BigIntegerField()),
                ('campaign_id', models.PositiveIntegerField(blank=True, null=True)),
                ('level_id', models.BigIntegerField(blank=True, null=True)),
                ('role_id', models.BigIntegerField()),
                ('org_types_id', models.BigIntegerField()),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_smartphone', models.BooleanField(default=False)),
                ('job_group', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('sync_status', models.BooleanField(default=False)),
                ('deactivated_by', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
